---
title: "Facebook Report"
date: " Created: `r format(Sys.time(), '%A %B %d, %Y : %X')`"
output: pdf_document
time: !r Sys.time()
params:
  table: NA
  sentiment: NA
  docs: NA
  set_author: "Someone"
  # sentences: NA
  # emotions_one: NA
  # emotions_two: NA
author: "Conversation between You & `r params$set_author`"
---

```{r setup, include=FALSE}
library(syuzhet)
library(tm)
library(jsonlite)
library(ggplot2)
library(knitr)
library(kableExtra)
# knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(comment = NA)
```

\begin{center}
Facebook Analysis Report
\end{center}
\begin{center}
```{r,echo=FALSE, warning=FALSE}
 table_one<- params$table

     sentimentscores <- sort(round(colSums(prop.table((table_one[,1:8])))*100,digits = 2),decreasing = TRUE)
     # print(sentimentscores)
     ##Create a dataframe that contains the sentiment scores
     sentimentscores <- as.data.frame(sentimentscores)
     ##Rename the column names of the sentiment scores
     colnames(sentimentscores) <- c("Emotional %:")

     ##Rename the row names of the sentiment scores
     Emotions <- c("anger","anticipation","disgust","fear","joy","sadness",
                   "surprise","trust")

 # pander::pandoc.table(sentimentscores)
 knitr::kable(sentimentscores)

```

\end{center}

```{r,echo=FALSE,warning=FALSE}
table_two <- params$table
sentiment<- params$sentiment
    if(is.na(sentiment$Percentages)){
      print("No bar plot created")
    }else{
    # value <- get_nrc_sentiment(table_two)
    sentimentscores <- round(colSums(prop.table((table_two[,1:8])))*100,digits = 2)
    # print(sentimentscores)
    ##Create a dataframe that contains the sentiment scores
    sentimentscores <- as.data.frame(sentimentscores)
    # print(ceiling(max(sentimentscores)))
    ylim_max <- ceiling(max(sentimentscores,na.rm = TRUE))
    # # ylim_max <- as.data.frame(sentimentscores,)
    ylimers <- c(0,ylim_max)
    # print(ylimers)
    barplot_one<- barplot(
       sort(colSums(prop.table(table_two[, 1:8])),decreasing = T),
       cex.names = 0.7,
       las = 1,
       main = " Emotional Sentiment by Word",
       col = "lightgreen"
       ,xlim = c(0,10)
       ,ylim = c(0,.40)
       # ,names.arg = round(x = sort(colSums(prop.table(value[, 1:8]))),digits = 2)

     )
    text(barplot_one, 0,labels = sort(round(colSums(prop.table(table_two[, 1:8])),digits = 2),decreasing = T),cex=1,pos=3)
    }

```

\newpage

\begin{center}
```{r,echo=FALSE, warning=FALSE}
 table_one<- params$table

     ##Create the sentiment scores table
     sentimentscores <- sort(round(colSums(prop.table((table_one[,9:10])))*100,digits = 2),decreasing = TRUE)
     # print(sentimentscores)
     ##Create a dataframe that contains the sentiment scores
     sentimentscores <- as.data.frame(sentimentscores)
     ##Rename the column names of the sentiment scores
     colnames(sentimentscores) <- c("Emotional %:")

     ##Rename the row names of the sentiment scores
     Emotions <- c("anger","anticipation","disgust","fear","joy","sadness",
                   "surprise","trust")

 # pander::pandoc.table(sentimentscores)
 knitr::kable(sentimentscores)
```
\end{center}


```{r,echo=FALSE,warning=FALSE}
table_three <- params$table
sentiment<- params$sentiment
    if(is.na(sentiment$Percentages)){
      print("No bar plot created")
    }else{
     barplot_two<- barplot(
        sort(colSums(prop.table(table_three[, 9:10])),decreasing = TRUE),
        cex.names = 0.7,
        las = 1,
        main = " Emotional Sentiment by Word",
        col = "lightgreen"
        ,xlim = c(0,3)
        ,ylim = c(0,1)
        # ,names.arg = round(x = sort(colSums(prop.table(value[, 9:10]))),digits = 2)

      )
text(barplot_two, 0,labels = sort(round(colSums(prop.table(table_three[, 9:10])),digits = 2),decreasing = TRUE),cex=1,pos=3)
    }
```


```{r,echo=FALSE,warning=FALSE}
    docs<- params$docs
    s_v <- get_sentences(docs)
    s_v_sentiment <- get_sentiment(s_v)
    plot(
      s_v_sentiment,
      type="l",
      main= paste0(name," Messenger Timeline"),
      xlab = "Messenger Timeline",
      ylab= "Emotional Valence"
    )
```


